config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks

  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to bookmarks_path
  end

  private

  def params_bookmark
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
  end

  def create
    list = List.create!(params_list)
    redirect_to list_path(list.id)
  end

  private

  def params_list
    params.require(:list).permit(:name, :review)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmarks</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/show.html.erb
<h2><%= @bookmark.name %></h2>
<%= link_to "Edit",
  new_bookmark_path(@bookmark),
  data: {turbo_method: :edit, turbo_confirm: "is it O.K?"}
%>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>
<% @lists.each do |list| %>
  <%= link_to list.name, list %>
<% end %>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for [@movie, @list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<%= link_to "Edit",
  edit_list_path
%>
<br>
<p><strong>Bookmarks</strong></p>
<ul class="list-group">
  <% @bookmarks.each do |bookmark| %>
    <li class="list-group-item"><%= bookmark.comment %></li>
  <% end %>
</ul>
<%= link_to "Write new bookmark here",  new_list_bookmark_path(@list) %>

app/views/movies/index.html.erb
<div><% @movies.each do |movie| %>
    <h3><%= link_to movie.title, movie_path(movie) %></h3>
    <h3><%= movie.title %></h3>
    <h3><%= movie.overview %></h3>
    <h3><%= movie.poster_url %></h3>
    <h3><%= movie.rating %></h3>
  </div>
<% end %>